packages:
  - packages/*

catalog:
  '@biomejs/biome': ^2.4.4
  '@types/react': ^19.2.14
  '@types/react-dom': ^19.2.3
  '@ungap/structured-clone': ^1.3.0
  '@vitejs/plugin-react': ^5.1.4
  classnames: ^2.5.1
  framer-motion: ^12.34.3
  react: ^19.2.4
  react-dom: ^19.2.4
  sharp: ^0.34.5
  typedoc: ^0.28.17
  typedoc-plugin-markdown: ^4.10.0
  typescript: ^5.9.3
  vite: ^7.3.1
  vite-plugin-dts: ^4.5.4
  vite-plugin-svgr: ^4.5.0
  vite-plugin-wasm: ^3.5.0
